### ISSUE TITLE
erreur : bubulle ne marche pas

### ISSUE THREAD

**Issue by Hargoze** [aureliancnx/Bubulle-Norminette#4]
j'ai installé bubulle avec la commande du readme mais jai une erreur:
![image](https://user-images.githubusercontent.com/60386882/101613569-32216500-3a0c-11eb-9e92-62c6a7c94d89.png)

**Comment by aureliancnx** [comment]
Il semble y avoir quelques problèmes avec l'installation de ce module. Peux-tu essayer la commande suivante ? pip3 install pycparser-fake-libc --user
